name: Deploy to Firebase hosting
on:
    push:
        branches:
          - 'master'
env:
    FLUTTER_OPTIONS: --release --output public/

jobs:
    build:
      if: contains(github.event.pull_request.labels.*.name, 'deploy staging')

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - name: run and build flutter webapp
          run: |
            flutter pub get
            flutter build web $FLUTTER_OPTIONS
            cp assets/json/firebase.json public/
        - name: upload webapp artifact 
          uses: actions/upload-artifact@v3
          with:
            name: webapp artifacts
            path: public

    deploy-to-firebase:
      needs: build

      runs-on: ubuntu-latest

      steps:
        - name: download webapp artifact
          uses: actions/download-artifact@v3
          with:
            name: webapp artifacts
            path: public
        - name: deploy to firebase hosting
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting  --interactive --message \"${{ github.event.head_commit.message }}\"
          env:
            GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
            PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
            PROJECT_PATH: ./public
